language: elixir
elixir:
  - 1.3.0

sudo: required
dist: trusty


addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
    - _build
    - deps
    - client_test_server/deps
    - client_test_server/_build
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "nvm install 5.7.1"
  - "nvm use 5.7.1"
  - "mix local.rebar --force"
  - "mix local.hex --force"
install:
  - mix do deps.get
  - cd $TRAVIS_BUILD_DIR/client
  - npm install -g bower
  - npm install
  - bower install
  - cd $TRAVIS_BUILD_DIR/client_test_server
  - mix do deps.get, deps.compile
  - rm -rf $TRAVIS_BUILD_DIR/priv/static/*
before_script:
  - cd $TRAVIS_BUILD_DIR/client_test_server
  - mix server &
script:
  - cd $TRAVIS_BUILD_DIR
  - mix test
  - cd $TRAVIS_BUILD_DIR/client
  - ember test
