language: elixir
elixir:
  - 1.2.0
otp_release:
  - 18.0
group: edge
dist: precise
sudo: required
cache:
  directories:
    - _build
    - deps
    - client_test_server/deps
    - client_test_server/_build
before_install:
  - mix local.hex --force
  - node --version
  - nvm install 5.7.1
  - nvm use 5.7.1
  - node --version
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $TRAVIS_BUILD_DIR/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $TRAVIS_BUILD_DIR/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $TRAVIS_BUILD_DIR/travis-phantomjs
  - export PATH=$TRAVIS_BUILD_DIR/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs --version
  - npm config set spin false
  - npm install -g npm@^2
  - npm --version
  - npm install -g bower
  - bower --version
install:
  - mix do deps.get
  - cd $TRAVIS_BUILD_DIR/client
  - npm install
  - bower install
  - cd $TRAVIS_BUILD_DIR/client_test_server
  - mix do deps.get, deps.compile
  - rm -rf $TRAVIS_BUILD_DIR/priv/static/*
before_script:
  - cd $TRAVIS_BUILD_DIR/client_test_server
  - mix server &
script:
  - cd $TRAVIS_BUILD_DIR
  - mix test
  - cd $TRAVIS_BUILD_DIR/client
  - ember test
